### ISSUE TITLE
Prioritize and fix issues from PageSpeed Insights

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#116]
Here's the link: https://pagespeed.web.dev/report?url=https%3A%2F%2Fbots.law%2F

There's probably a couple dozen things we could do there to make it better/faster. Not all of them will be worth the effort or will be easy, but they're worth looking at.

**Comment by ERosendo** [comment]
Here are the new scores after merging https://github.com/freelawproject/bigcases2/pull/162:

**Mobile:**

- Before:
 ![image](https://user-images.githubusercontent.com/55959657/228692832-2669d89f-a55d-439e-ab20-2aa1685c21e8.png)  

- After:
 ![image](https://user-images.githubusercontent.com/55959657/228692748-b2efaba5-7f1a-4ece-af79-37acdea5287e.png)  


**Desktop:**

- Before:  
![image](https://user-images.githubusercontent.com/55959657/228693539-504bb0f9-f6ad-4df5-bb9f-9336c74c5282.png)  

- After:
 ![image](https://user-images.githubusercontent.com/55959657/228693419-06f83ed7-a90b-4d79-86bf-c2ac2d9c9632.png)

**Comment by mlissner** [comment]
I think the one remaining thing is adding height/width to our images. I don't see much else.

**Comment by mlissner** [comment]
Per #151, I think we're done here. Our scores are fantastic.
