### ISSUE TITLE
Make the new website good

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#119]
Over in #113, we're doing some clean up stuff, but we still have a lot to do to make the site really good. Among them:

 - Compile and deploy tailwind in our CI pipeline (#110)
 - Invalidate cache on deployment (#114)
 - Make the PageSpeed insights happy (#116)

Once that's done, it's onwards to all the pages the site needs. Most of these will just be text with a picture or two, but some will need dynamic content (these will need to avoid being cached by CloudFront via a django decorator on the view). 

Anyhow, these are the pages and components we need:

  - [x] The Big Cases header drop down should offer two drop down options: 
      - "About" (`/big-cases/about/`): This will have information about the history of the bot, the curators, and the list of cases followed.
      - "Sponsors" (`/big-cases/sponsors/`): This will have information about the Sponsorship program, past sponsors, etc.

    We'll need to update the footer to just link to these two places as well.

 - [x] The Little Cases header will just go to `/little-cases/`, which will have a simple page explaining that we aim to let other people set up bots too, and providing a form for people to "Suggest a Bot". The form could just ask the person's name, preferred platforms (checkboxes for mastodon, or twitter) and a free text box that asks them for the kinds of cases it would follow.

    Eventually, when we have our first Little Cases bot, we'll have to provide links saying who maintains each, what cases each is following, etc. 

    At first, it'll probably be hands on creating Little Cases bots, but ideally we'll make it totally hands off over time.
 
 - [x] The Collaboration Suites header goes to `/collaboration/` and provides a page explaining the features we aim to have in Slack, Discord, etc. This is something of a product page, and it has a form to sign up for the waitlist. The form asks for your preferred platforms (slack, discord, MS Teams, or Google Chat), contact info (name and email), and company name (optional)

 - [x] Donate link is good to go for now.

 - [x] Sign In link should go away for now. We're not ready for it, but we should at least get `/sign-in/` working so we can get the django admin page up and running. We'll eventually need the full suite of user-handling junk, unfortunately, but we can put it off for now since it involves setting up email and everything else. We'll need it for Discord/Slack/etc though.

 - [x] The Join the Waitlist button simply takes you to `/collaboration/#join`, and we can put a node with `id="join"` on the form.

 - [x] The Learn More links:
     - The one under Big Cases takes you to /big-cases/about/
     - The one under Little Cases takes you to /little-cases/
     - The one under Free, Searchable Documents takes you to `/big-cases/my-code/`

        This page explains how Big Cases bot is a demonstration of what can be done using the RECAP Suite, and goes into how RECAP works, how Big Cases Bot is an open source project, how the Webhooks and Doctor fit in, etc. 

        In the footer, we can remove the section for "INSIDE ME", and simply put a link under the Big Cases footer that says "How I Work", that links to `/big-cases/my-code/`

 - [x] In the footer:
    - The links under Big Cases should mirror the ones in the drop down.
    - The Inside Me section goes away, replaced as explained above.
    - The Colaboration header is spelled wrong again, and I guess we should just put a link in there for "Join the Waitlist" and "Learn More"
    - RECAP should be capitalized.
    - Data services can be removed.
    - Other Projects on Github can be changed to "More on GitHub" (note that Hub is capitalized)
    - Build your own bot should be title case, and link to the `/little-cases/` URL.
    - Follow the FLP blog goes to https://free.law/blog/

I think that's it for the next round. For the various pages that will need text, I'll work on them if you provide me with a stub where I can plug in a header and some text.

**Comment by ERosendo** [comment]
We can close this issue. The following PRs add the components listed above:


- https://github.com/freelawproject/bigcases2/pull/131
- https://github.com/freelawproject/bigcases2/pull/135
- https://github.com/freelawproject/bigcases2/pull/141
- https://github.com/freelawproject/bigcases2/pull/137
- https://github.com/freelawproject/bigcases2/pull/138

**Comment by mlissner** [comment]
I guess I better start writing some danged pages. Thank you, closing!
