### ISSUE TITLE
Weekly email round-up

### ISSUE THREAD

**Issue by anseljh** [freelawproject/bigcases2#12]
Automated or curated?

**Comment by mlissner** [comment]
What's the idea here, Ansel? Can you expand on what you have in mind, please?

**Comment by anseljh** [comment]
It's not a very well-developed idea. Just see which cases had the most
engagement on CL or on social media, and highlight them.

A further step could be to add some narrative about them, but that's work.
@colarusso is doing interesting work on using a LLM to generate summaries,
but he still edits them:
https://icymilaw.org/about/#pod

I'd put this on the back burner.

**Comment by mlissner** [comment]
People have been asking for similar on CL for ages and I just don't know enough about ranking systems.

**Comment by mlissner** [comment]
This is duped with more detail by https://github.com/freelawproject/foresight/issues/14
