### ISSUE TITLE
Document RSS feeds from Mastodon

### ISSUE THREAD

**Issue by anseljh** [freelawproject/bigcases2#13]
This implies there is a web server doing more than webhooks.

**Comment by anseljh** [comment]
Actually, we get this for free from Mastodon! Just tack `.rss` onto the end of the username, like: https://law.builders/@bigcases.rss
🤯

**Comment by mlissner** [comment]
Is it worth leaving this open as a documentation feature to realize?

**Comment by mlissner** [comment]
Ansel, I just pushed a bunch of changes to the Big Cases website, but I didn't see a great place to put this. Want to take a look at the new site and suggest something (or submit a PR, if you're up for it)?

**Comment by mlissner** [comment]
Mastodon seems to be a dud at least for bots.law, so I'm disinclined to bother with this. Also seems like if you want to follow BCB, you can do so in numerous ways and if you're an RSS person, it's not our job to advertise Masto's features.
