### ISSUE TITLE
Implement periodic funding appeals and advertising system

### ISSUE THREAD

**Issue by anseljh** [freelawproject/bigcases2#14]

**Comment by mlissner** [comment]
I think the way to do this will be via the last thumbnail of documents that we purchase. When our budget is low, we put an appeal in that spot that says to donate or sponsor the bot, and provides a link. 

Once somebody has sponsored the bot for, say $1,000 we spend the majority of that on purchasing documents (90%?) and keep the remainder for our troubles. As the $900 is used, we put something like "Sponsored by XYZ" on the bottom of each thumbnail in a fairly unobtrusive way. 

We'll see if that winds up violating Twitter's TOS, but I think we can probably get away with it for a while.

**Comment by mlissner** [comment]
Closing this. I'm going to organize this feature differently via a couple other issues.
