### ISSUE TITLE
Yank the view_docket view/template or prove its purpose

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#144]
Does this have a use-case that I don't know about? Why do we have it? Should we remove it?

**Comment by ERosendo** [comment]
We got this page from the flask version of the bot. We refactored the page into a view and a template and this page was supposed to show details about a case (like the name of the user who requested the case, and the channels the bot is using to create posts about it).

**Comment by mlissner** [comment]
OK, I think we don't need this, at least not for now. Let's yank it, so we don't have half-done ideas floating around.
