### ISSUE TITLE
Integrate with DocumentCloud if there is interest

### ISSUE THREAD

**Issue by anseljh** [freelawproject/bigcases2#15]
If we have journalist curators, they may want to also store things in DocumentCloud. We should ask them.

See:

- https://github.com/freelawproject/bigcases2/issues/7#issuecomment-1332935806
- #6 
- #8 

Brad used Muckrock's [`python-documentcloud`](https://documentcloud.readthedocs.io/en/latest/) package.

**Comment by mlissner** [comment]
No journalist has mentioned this, not once. I think we can close it.
