### ISSUE TITLE
Add watermarks and thumbnails to sponsored documents

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#151]
When we start buying documents in #16, we need to add watermarks to them. It'll work like this:

1. If it's sponsored by an organization, the documents will get a watermark on them that says the organization's name: "Sponsored by ".

2. If it's sponsored by FLP, there's no watermark, but any document with fewer than 4 pages gets an extra thumbnail at the end. That thumbnail says that the document is sponsored by Free Law Project, provides a link to the sponsorship page (maybe a QR code?) and encourages others to sponsor the bot.
    - If the document has four or more pages, we don't do this, and we provide the regular thumbnails with no watermark.

3. If the document isn't sponsored at all, then we can do a thumbnail every so often saying that we need sponsors, but I think it's more elegant to handle this by email, and we should do it that way. So in this case, no thumbnail at all, just like we do now.

I think that should do the trick.

**Comment by ERosendo** [comment]
I've reviewed a few articles about pictures with watermarks, and most of them agree that the bottom right is the most popular position that photographers, and other people often choose to put a watermark. 

Here are a few posts with watermarked thumbnails. I used the same font We've been using to create the images when the document's description is longer than the maximum number of characters in the post, and I set the font_size to 32 ( I tried using 16px but the text was really small using that font size). 

- position: bottom-left corner
    - opacity 25% https://twitter.com/flp_tests/status/1643747088801443842
    - opacity 50% https://twitter.com/flp_tests/status/1643763787189608449

- position: bottom-center
    - opacity 25% https://twitter.com/flp_tests/status/1643724153248178176
    - opacity 50% https://twitter.com/flp_tests/status/1643760645333045255

- position: bottom-right corner
   - opacity  25% https://twitter.com/flp_tests/status/1643751150330494979
   - opacity 50% https://twitter.com/flp_tests/status/1643752554612891649

**Comment by ERosendo** [comment]
I added color ( light orange - #FE8D01) to the footer and here are the results : 

- This footer is centered at the bottom of the thumbnail https://twitter.com/flp_tests/status/1643772680565411841
- This footer is left aligned at the bottom of the thumbnail https://twitter.com/flp_tests/status/1643773471078400001

John noticed footers are not visible in the default Twitter crop. I tried to resize the thumbnails to avoid the crop. Here's the result (the ideal aspect ratio for each thumbnail depends on the number of images included in the tweet ):

- This tweet has 3 images so the first image appears larger (in 7:8 ratio) and the other two in 4:7 ratio. https://twitter.com/flp_tests/status/1643786185221763080

I also noticed a lot of people put many watermarks across their photos when they are selling them on the web. I tried that approach and here's a post on Twitter: https://twitter.com/flp_tests/status/1643791967728332801. If We use this approach We don't have to worry about the default Twitter crop.

Let me know what you think.

**Comment by mlissner** [comment]
These are good examples, thanks. Poking around on them, some thoughts:

 - The orange color is the right idea, but probably should be darker. 
 - The watermarks in the background are both too annoying and too subtle. Can't say I like them, sorry.
 - Centering feels better than right or left. 
 - Text size seems...ok. Maybe a bit larger would be OK?
 - I haven't seen the opacity do anything except make our text lighter, since it's always on a white background.
 - I don't *think* John was serious about adjusting the crop, but in any case, it doesn't seem to be a good idea, since it makes reading them quite difficult.

I *also* don't know if John was serious about doing the words vertically, but I think it's worth trying, since there's almost always a margin on the side, and that'd fix the visibility problem? Want to try that on the left, centered vertically?

I

**Comment by ERosendo** [comment]
Thanks for your comment. I tweaked the code to create the text on the edges of the page. Here are a few examples:

- Text on the left edge of the page: https://twitter.com/flp_tests/status/1643988742355689478
- Text on the right edge of the page: https://twitter.com/flp_tests/status/1643988356257423366
- Text on both edges of the page: https://twitter.com/flp_tests/status/1643986625746317323

Let me know what you think.

**Comment by mlissner** [comment]
I like the right best. It feels like the right balance of attention-seeking, and easy-to-ignore, since we read from left to right. 

Can you make a few tweaks though:

 - Make it smaller, please.
 - Not uppercase
 - Add a second smaller line below the first that says, "Learn more at https://bots.law/big-cases/sponsors/"

I think we're getting there. Thanks for continuing to tweak.
