### ISSUE TITLE
Add captions/alt-text to document thumbnails

### ISSUE THREAD

**Issue by anseljh** [freelawproject/bigcases2#17]
Captioning is great, and also a stronger convention in Mastodon. 

See, e.g., https://botsin.space/@PleaseCaption.

**Comment by mlissner** [comment]
We can only do this for documents we have when we send our toot/tweet, but we should build it in early because it's pretty easy. 

We could use doctor to get the text, but I think it's probably more performant to get it from the CL API.

**Comment by mlissner** [comment]
Actually, I don't think we should bother getting the text of the documents. It's too much trouble and people will have the link to the doc right there. We can just say:

> Thumbnail of page 1

> Thumbnail of page 2

Etc.
