### ISSUE TITLE
Custom 404 and other error pages

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#182]
Right now our 404 pages just return generic Not Found errors. We should probably do better by at least displaying a nicer page with, ya know, some HTML and CSS.

We could go wild with this, but I guess for now the example on free.law is fine.

**Comment by ERosendo** [comment]
I checked the 404 page for free.law and I think We can use the following one for bots.law



![Image](https://user-images.githubusercontent.com/55959657/231917994-7e40893d-8ef7-4b83-8aa4-2626dff09093.png)




Let me know what you think.

**Comment by mlissner** [comment]
This would be fine, though I think I'd say that "the requested *page* cannot be found"

And I'm still holding out hope that somebody can do a better joke for this page, per discussion in #flp-general-chat.

**Comment by mlissner** [comment]
OK, I think @mattdahl has the winning proposal. Let's tweak this to say:

> # 404 Droid Not Found
> 
> [Sorry, this is not the page you're looking for](https://www.youtube.com/watch?v=532j-186xEQ).

With the link the same color as the rest of the text, so it's a bit hidden unless you mouse over it. 

The rest is great.
