### ISSUE TITLE
Link Subscriptions, Sponsorships, and Users to Channels

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#220]
Right now, we have Subscriptions which represent things that bots in the Channels table post about and we have Sponsorships, which pay for things bots in the Channels table want to post about. This all works well, but assumes that the bots in the Channels table are special. 

They are, but not for long! When we introduce Little Case bots, we need to introduce a new layer to link things together better. 

I just looked at our models a bit and I think this requires two changes:

1. A new m2m table between sponsorships and channels.
2. A new m2m table between subscriptions and channels.
3. A new m2m table between users and channels.

That's not too tough, but we'll also need to adapt the Python code, so:

1. The `lookup` command uses God mode, so it just needs a new flag for which channels to subscribe a new case to (default the Big Cases channels, though I suspect this command won't be used much soon). I think the `post` command lets you choose channels already and might be useful prior art?

2. The new subscription page needs a way for the user to select the correct channels for the subscription. I'm not sure the best way to do this. Maybe show checkboxes on the page for each channel the user has access to, with all of them checked by default? This will be annoying for Big Cases maintainers, but good for everybody else.

3. The webhook endpoint needs to be tweaked to only buy content when the case is part of a sponsored channel. If a case has more than one sponsorship, the cost should be divided evenly and watermarks should be created for each sponsor. For example:

   - Big Cases and Tech Cases are both subscribed to Samsung v. Apple.
   - Big Cases is sponsored by FLP and Tech Cases is sponsored by IBM.
   - A new doc comes in that costs $1.
   - FLP pays 50¢. IBM pays 50¢.
   - The post to Big Cases says sponsored by FLP.
   - The post to Tech Cases says sponsored by IBM.

    Sponsorship labels should not bleed across channels. So:
  
   - Big Cases is sponsored, but Tech Cases is not.
   - Both are following Samsung v. Apple.
   - Big Cases buys the document.
   - The post to Big Cases says sponsored by FLP.
   - The post to Tech Cases has the doc, but no sponsorship info.

5. What else? We're getting into the tricky stuff now!

**Comment by mlissner** [comment]
Another problem I'm noticing is that we probably need a system to link channels together. For example, right now the Big Cases page just shows ALL of the subscriptions. After we add a Little Case, it needs to only show the subscriptions for Big Cases, not for the other new bots. How do we do that?

Another thing: Right now, the Little Cases page is a placeholder. When we launch our first Little Case bot, we'll need to publicly show (with a unique URL) the cases it's following. If it's on Mastodon and Twitter, how do we generate that page? Somehow, somewhere, we need some sort of "meta channels" object that links channels together.

As far as modeling this goes, I think the easiest way to do this is to add a nullable `alias_of` field and self-join to the Channels table:

`id` | `alias_of` | `service` | `account` | `account_id` | ...
---|---|---|---|---|---
1|null|Twitter|`@big_cases`|whatever|...
2|1|Mastodon|`@bigcases@law.builder`|whatever|...

This would mean that channel 2 is an "alias" of channel 1. They're both Big Cases stuff, but Channel 1 is the primary channel in some sense.

Once that's in place, we could also use this in various places:

1. The `lookup --add` and `post` commands could default to channels where `alias_of` is null, and then post to all channels aliased to the selected channel too. So it'd suggest channel 1 (Big Cases) or channel 3 (Tech Cases), you'd pick channel 1, and it'd go out to channel 1 and 2.

2. Similarly, the new subscribe page could just show checkboxes for the unaliased channels.

3. The subscribed case pages for Big Cases and Little Cases would do similar (solving the problem identified above).

**Comment by mlissner** [comment]
Sounds good. I agree, thank you.

**Comment by ERosendo** [comment]
> The new subscription page needs a way for the user to select the correct channels for the subscription. I'm not sure the best way to do this. Maybe show checkboxes on the page for each channel the user has access to, with all of them checked by default? This will be annoying for Big Cases maintainers, but good for everybody else.

I think checkboxes are the best option for cases like this and We can show the channels grouped by Alias. The new form would look like this:


![image](https://user-images.githubusercontent.com/55959657/236112181-73bfa181-ed8e-4bfd-9fc0-614927845047.png)

Let me know what you think

**Comment by mlissner** [comment]
That makes sense to me. Does the alias name go in the alias table?

**Comment by ERosendo** [comment]
Yes. the name is stored in the alias table.
