### ISSUE TITLE
Add thumbnails for documents that are available when we post

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#23]
I'm not sure if this is already ready, but we can launch without it, so I'm setting it as a post launch milestone that we can do later.

**Comment by mlissner** [comment]
I think the trick for this one is to build in a small delay between when we get a webhook event from CL and when we send our social posts. During that delay, somebody might buy the document and if they do, we can download it, make thumbnails, etc. If the delay is configurable, we can tweak it to see how big of a delay actually helps.

**Comment by ERosendo** [comment]
We're using the `enqueue_in` method to [schedule](https://github.com/rq/rq-scheduler#scheduling-a-job) the execution of the function that sends the social posts. 

We also have a variable in the .env file called `WEBHOOK_DELAY_TIME` to set the delay in seconds. Here's the code We're using to schedule a task:

https://github.com/freelawproject/bigcases2/blob/bcbf9f64026882637e685303a6913bb376b06a75/bc/subscription/api_views.py#L59-L63
