### ISSUE TITLE
Set up a webhook endpoint to receive CL webhook events

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#25]
I don't know if this exists yet and if so whether it works, but my assumption is it doesn't exist or doesn't work, so here's an issue to track the feature.

**Comment by mlissner** [comment]
At first, this could simply log them or store them in the DB. It wouldn't need to actually *do* anything, I think.

**Comment by anseljh** [comment]
It does exist :)
https://github.com/freelawproject/bigcases2/blob/main/bigcases2/courtlistener.py#L42

**Comment by mlissner** [comment]
Should have known! Sounds like this will be an easy issue to close (famous last words).

**Comment by mlissner** [comment]
I guess if we're looking at this, we should at least glance at #40, though, note that it's marked as post-release.
