### ISSUE TITLE
Post to Twitter

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#26]
Twitter is where our audience is, so it'll come first, and I'll open another ticket to post to mastodon next. One thing at a time. 

We can use the examples from the original big cases bot to create the text of the links. 

When we launch, we won't be buying content, so let's just use our links that go to PACER if we don't have something and upgrade to the PDF once we do. Here's an example:

https://www.courtlistener.com/docket/66696476/01208457368/shawn-musgrave-v-mark-warner/?redirect_to_download=True

**Comment by mlissner** [comment]
I take that back. We'll do mastodon first because that's where the audience is *not*, and we can make mistakes there. I'll reprioritize in the queue.

**Comment by ERosendo** [comment]
@mlissner I was about to make the same comment related to mastodon. I think We discussed this previously and agreed to do mastodon first.

**Comment by mlissner** [comment]
Let's not do this until we know how much the Twitter API will cost. Maybe we won't wind up doing this. 🤡

**Comment by ERosendo** [comment]
Our test account is still waiting for approval 🙃

![image](https://user-images.githubusercontent.com/55959657/225650957-faf2e5ff-f746-4842-b585-4e54a88f0f05.png)

**Comment by mlissner** [comment]
What about using Bill's? Did that get sorted out?
