### ISSUE TITLE
Tailwind checkbox image violates CSP

### ISSUE THREAD

**Issue by cweider** [freelawproject/bigcases2#297]
<img width="1735" alt="Screenshot 2023-07-03 at 1 01 10 PM" src="https://github.com/freelawproject/bigcases2/assets/45040/32075e09-58a4-4b36-b7d4-fc1ad5c62d8c">

**Comment by mlissner** [comment]
Perfect

**Comment by cweider** [comment]
This is caused by `@tailwindcss/forms` plugin, which [uses data URIs for form elements in CSS](https://github.com/tailwindlabs/tailwindcss-forms/blob/master/src/index.js#L228). Fix is to except `data:` for `image-src`. This is not great, because `data:` can, literally, be anything, but images have limited scope for bad behavior and so, it’s not a pressing concern.

**Comment by mlissner** [comment]
Hm I just tried to trigger this so we could test the new CSP reporting, but couldn't do so. At least just loading the page wasn't enough in Chrome...

**Comment by ERosendo** [comment]
@mlissner You have to click the checkbox to trigger the error. :)

Here's the issue from Sentry:

[Blocked 'image' from 'data:'](https://freelawproject.sentry.io/issues/4296050084/?project=4504573893738496&query=is%3Aunresolved&referrer=issue-stream&stream_index=0)

**Comment by mlissner** [comment]
Got it. Cool!
