### ISSUE TITLE
Custom fonts blocked by CORS policy in Chrome

### ISSUE THREAD

**Issue by cweider** [freelawproject/bigcases2#326]
<img src="https://github.com/freelawproject/bigcases2/assets/45040/d9733081-9c53-4fa0-8692-0bc7b2bd0000">

Chrome appears to be more off a stickler than other browsers w.r.t. Fonts. Regardless, that is the spec: [W3C CSS Fonts # Font fetching requirements](https://www.w3.org/TR/css-fonts-3/#font-fetching-requirements)

> The implications of this for authors are that fonts will typically not be loaded cross-origin unless authors specifically takes steps to permit cross-origin loads. Sites can explicitly allow cross-site loading of font data using the `Access-Control-Allow-Origin` HTTP header. For other schemes, no explicit mechanism to allow cross-origin loading, beyond what is permitted by the potentially CORS-enabled fetch method, is defined or required.

…a few adjustments to the static upload process are needed.

**Comment by ERosendo** [comment]
Hey @cweider, That's weird. I don't get those issues using Chrome version 114.0.5735.198 (arm64).

<img width="1512" alt="Screenshot 2023-07-07 at 1 32 40 PM" src="https://github.com/freelawproject/bigcases2/assets/55959657/89dd7406-84ce-4a23-af75-e3c6c1c92daf">

**Comment by mlissner** [comment]
Disquieting.
