### ISSUE TITLE
More enhancements to "I'm now following" posts

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#332]
I just added a new case for the bot to follow and it dutifully sent out an "I'm now following..." tweet. That's good, but there's a bit of missing context: The bot wasn't following the case until just recently, even though the case was opened over a year ago.

We should add a date stamp to the "I'm now following..." tweets for any case that's older than a month. This should be easy. Just get the date_filed field from the docket object via the API, do a comparison, and then add that bit of context, if needed.

The NYT times does this on its older articles. When you read them, there's a warning at the top that they're old. I think the Guardian does something like this too.

**Comment by mlissner** [comment]
Another change we should do is to include the initial complaint, not just photos of it. So, it should say:

```
Docket: xyz

Complaint: xyz

Context: xyz
```

I think we still have space for that! 

This came up recently when somebody replied to our "I'm now following..." post with a link to the complaint. I was like, what?

**Comment by TheCleric** [comment]
@mlissner looking at this, but I have a question. For something like `enqueue_posts_for_new_case` it's going off the `Subscription` for the case. Do we want to:
1. start saving the `date_filed` there (and possibly backfill it as we go)
1. or just make a call out to CL every time to get the `date_filed`

Option 1 seems like the better one to me, but I'm not sure how you folks feel about messing with database schema (and potentially ugly backfill code).

**Comment by mlissner** [comment]
Yeah, good questions, we could:

 - Pass the date_filed into the method, if we have it.
 - Cal out to CL within the method
 - Add it to the Subscription object

I think tweaking the DB and taking the third option is fine. We don't need to backfill, and it keeps the python code tidy. Works for me. 

@ERosendo, what do you think?

**Comment by mlissner** [comment]
It's already finding the initial complaint and adding it as screenshots on the "I'm now following" posts. I think just use the same document as the one we're using for thumbnails? (Sorry, I forget how that area of the code works, but I think you should have the info you need already in there.)

**Comment by mlissner** [comment]
> As well I'm assuming that you wouldn't want to show the complaint link if this item IS the initial complaint, right?

Most of our "I'm now following" posts are around the time the case comes out. After that, it's in auto-drive mode, and it posts about whatever docs are filed in a given moment. So..I'm not sure I understand your question, sorry!

**Comment by TheCleric** [comment]
Sorry for not being clear: I was referring to this:

> Another change we should do is to include the initial complaint, not just photos of it. So, it should say:

So maybe I'm just confused what "initial complaint" means here?

**Comment by ERosendo** [comment]
I'm very sorry for joining the conversation this late.

> @ERosendo, what do you think?

I don't think we need to store the `date_filed` in the subscription model since it'll be only used for the initial announcement, we can retrieve it with an API request during the `check_initial_complaint_before_posting` task.

**Comment by ERosendo** [comment]
> how do I trace a new case back to its initial complaint?

@TheCleric we have a helper function named `lookup_initial_complaint` that can quickly retrieve the initial complaint.

https://github.com/freelawproject/bigcases2/blob/4c629d292394a2d84a9b8d7dad0496ea64fcd731/bc/subscription/utils/courtlistener.py#L150-L190

**Comment by ERosendo** [comment]
> As well I'm assuming that you wouldn't want to show the complaint link if this item IS the initial complaint, right?

The bot uses various pre-defined messages to create posts within channels. These messages can be categorized into two main groups:

- `Initial Announcement Templates`: used when the bot starts following a new case, these templates likely introduce the case to followers. Here's an example:

![image](https://github.com/freelawproject/bigcases2/assets/55959657/4add269c-9fd9-46ac-a99f-b2bf3d075f80)

- `New Document/Entry Templates`: used when **new** information is added to a case. 

The initial complaint is typically part of the case from the beginning so the bot won't create a `New Document/Entry` post for it. 

This issue focuses on tweaking the first group, the `Initial Announcement Templates`.  It's easy to identify these templates because all of them include the keyword `"FOLLOW_A_NEW_CASE"` in their names.

**Comment by ERosendo** [comment]
> So maybe I'm just confused what "initial complaint" means here?

@TheCleric I'm pretty sure it means we should add the link to the "initial complaint" within the message template, right @mlissner?

**Comment by TheCleric** [comment]
> This issue focuses on tweaking the first group, the Initial Announcement Templates. It's easy to identify these templates because all of them include the keyword "FOLLOW_A_NEW_CASE" in their names.

This is what I was thinking. Thanks for confirming.

**Comment by TheCleric** [comment]
Also it looks like to test any of this I would need access to the CL API. I signed up for an account and got an API key, but I don't think I have access to the right endpoints (such as the recap-documents one). I completely get not wanting to hand that out. Please advise on how you would like to handle.

**Comment by mlissner** [comment]
Totally. I just granted access to your account. Thank you!
