### ISSUE TITLE
Fix hashtags in BlueSky posts

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#514]
They added hashtags, but you have to, like, attach them to the posts, not just put them in the text of the posts, so we need to tweak how we do this. 

Luckily, we applied for a microgrant with BlueSky and got it, so this is actually funded work. Cool! 

We did this for Mastodon in https://github.com/freelawproject/bigcases2/issues/196, if that's helpful.

**Comment by mlissner** [comment]
I'm asking for "micro-applications" from the community to do this work: https://bsky.app/profile/free.law/post/3kqgrb5om4p2b

**Comment by Woovie** [comment]
Hello, I saw your Bluesky post. I do not expect to have time to implement, but here's a some research into the codebase and Bluesky posts in case someone else does:

- https://docs.bsky.app/docs/advanced-guides/post-richtext
- [This seems to be the specific place in which a hashtag facet would be injected, along side the LinkFacet class.](https://github.com/freelawproject/bigcases2/blob/main/bc/channel/utils/connectors/bluesky_api/types.py#L64-L71)
- [Parsing of the links for building facets seems to happen here.](https://github.com/freelawproject/bigcases2/blob/main/bc/channel/utils/connectors/bluesky_api/client.py#L182-L232)

**Comment by mlissner** [comment]
The inventor of hash tags chimes in: https://bsky.app/profile/chrismessina.me/post/3kqixpo5rjk2h
