### ISSUE TITLE
Adding mypy to the pre-commit hook

### ISSUE THREAD

**Issue by TheCleric** [freelawproject/bigcases2#522]
I noticed that mypy was not running on the pre-commit hook and a note saying it had been tried before without success. I experimented with what it would take to do this and was successful in getting it working. However I wanted to gauge the interest in adding this, since it comes with a few downsides that I think are important to think through.

### Upsides
- You get mypy ran before you commit to catch type errors

### Downsides
- It's a bit slower. In my test a commit with one `.py` file went from .68s to 1.11s, for two `.py` files it goes from .73s to 2.71s
- You have to keep a separate copy of some of the dependencies in the `.pre-commit-config.yaml` since mypy runs in an isolated environment for pre-commit. It ends up looking like this:

```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
     - id: mypy
       additional_dependencies: [
          beautifulsoup4==4.12.2,
          boto3==1.34.74,
          courts-db==0.10.17,
          django-debug-toolbar==4.3.0,
          django-environ==0.11.2,
          django-hcaptcha==0.2.0,
          django-htmx==1.17.3,
          django-rq==2.10.2,
          django-stubs==4.2.0,
          "django-tailwind[reload]==3.8.0",
          "Mastodon.py[cryptography]==1.8.0",
          pillow==10.3.0,
          psycopg2-binary==2.9.6,
          sentry-sdk==1.44.0,
          twitterapi==2.8.2,
          types-requests==2.31.0.1,
        ]
```

**Comment by mlissner** [comment]
Where was the note about trying it before? I don't recall what the problem was. That performance is a bit of a bummer, and might be enough of a problem in itself...

**Comment by TheCleric** [comment]
> Where was the note about trying it before? I don't recall what the problem was. That performance is a bit of a bummer, and might be enough of a problem in itself...

At the bottom of `.pre-commit-config.yaml`:

```
# Tried and Failed
#
# 1. I tried doing mypy too, but it was a mess because it runs in its own
#   isolated environment, that lacks all our dependencies.
```

**Comment by mlissner** [comment]
Got it. That's not horrible, but it's annoying to have to maintain the dependencies properly in both places. On the other hand, it's nice to have mypy running automatically, and I've certainly noticed I have a tendency not to bother with it until it crashes. 

I'm +1 on adding it here experimentally. We can see what people think, unless somebody chimes in to be -1 on it.

**Comment by TheCleric** [comment]
@mlissner just so I'm clear, does that mean to go ahead and submit a PR and get feedback then, or wait for feedback here?
