### ISSUE TITLE
Implement refresh mechanism for Threads access tokens

### ISSUE THREAD

**Issue by elisa-a-v** [freelawproject/bigcases2#627]
[This PR](https://github.com/freelawproject/bigcases2/pull/618) introduced support for Threads but the access tokens expire after 60 days unless refreshed.

[To refresh a token](https://developers.facebook.com/docs/threads/get-started/long-lived-tokens) we simply need to use the `GET /refresh_access_token` endpoint with the valid long-lived access token in the query params, which will refresh it for another 60 days.

The responses from the endpoints to get access tokens include `expires_in` with the number of seconds until the token expires. As discussed with @ERosendo, 

1. Once a new Threads channel is created, schedule a task to refresh the token in 2 days (because long-lived access tokens can be refreshed as long as they are at least 24 hours old).
2. Since you're refreshing the token from Django, you can retrieve the expires_in value from the response. Subtract one day from this value to compute the optimal time for the next task.
3. Use this calculated time to schedule the next token refresh task.

This way we don't have a hardcoded number that could be insufficient should Meta decide to change the validity duration for the tokens.

**Comment by mlissner** [comment]
Sounds like a nice design that avoids cronjobs and hardcoding. 👍🏻

**Comment by elisa-a-v** [comment]
For future reference, we ended up not implementing the solution described here but instead used redis to store the expiration date, and we validate the token (check expiration, refresh if necessary) every time we interact with the ThreadsAPI as described in [this comment](https://github.com/freelawproject/bigcases2/pull/629#issuecomment-2464719831).
