### ISSUE TITLE
GivingTuesday banner on bots.law

### ISSUE THREAD

**Issue by mlissner** [freelawproject/bigcases2#630]
Simple banner to run for one day at top of bots.law:

**Today is GivingTuesday.** Your support of Free Law Project helps make the justice system more transparent and accessible to all. **[Donate Today!](https://donate.free.law/forms/givingtuesday)**

This should merge on Tuesday, December 3, 2024

**Comment by elisa-a-v** [comment]
Any comments on this design?

![Image](https://github.com/user-attachments/assets/9500af16-dac7-422c-8069-b427a7c21616)
![Image](https://github.com/user-attachments/assets/600566e1-03a5-48cd-b571-24d099ff92ed)
