### ISSUE TITLE
Add EOY banner with settings to toggle visibility

### ISSUE THREAD

**Issue by elisa-a-v** [freelawproject/bigcases2#641]
The banner is currently hardcoded so toggling its visibility needs to be done in code which is obviously not ideal; we should have a setting that allows to toggle this without needing to change the code each time.

CL has a `FUNDRAISING_MODE` to toggle visibility so we can do the same here.

**Comment by elisa-a-v** [comment]
@mlissner I added these sub-issues so we can hide the GT banner ASAP since it's already quite late, but I have a question about this: does this banner also need to be dismissible like the one in CL? and do we also want it to reappear after one week like the [free.law EOY popup](https://github.com/freelawproject/free.law/issues/237)?

**Comment by mlissner** [comment]
Nah, doesn't need to be dismissable. Not enough traffic on bots.law.

**Comment by mlissner** [comment]
I think this is done?

**Comment by elisa-a-v** [comment]
@mlissner I added the setting to enable/disable the banner from the .env with a flag and it works fine, but I thought it could be a good idea to instead add a new model for managing the banner. We could move the flag there and also add fields for the title, text and button configs, so that way we could customize that from the django admin directly. what do you think? I think it should be pretty straightforward, and customizing the content would be way easier and it wouldn't even require a redeploy or anything.

**Comment by elisa-a-v** [comment]
well, I personally liked the model idea so I just went ahead and did that 😅 we can always roll it back to the `.env` commit which is in the same branch if that's better for you.

**Comment by mlissner** [comment]
Thanks for taking the initiative on this one, Elisa. The model approach is quite nice (but onwards to cache eviction!)
