### ISSUE TITLE
Crawling decisions

### ISSUE THREAD

**Issue by anseljh** [freelawproject/bigcases2#7]
- [ ] How often to update dockets
- [ ] Which documents to buy

**Comment by mlissner** [comment]
I assume this would work by using the PACER Fetch APIs: 

https://www.courtlistener.com/api/rest-info/#pacer-fetch

What I don't know is how we handle the money side if we set up a fund for this. I had a vision of BCB having a known budget that it spends, and then when it's out of money, it stops buying content and starts begging for more (or something like that). I guess bigcases.free.law/donate could go into a BCB-only pool, maybe. Too many options here.

The other thing to think about is that if we get *complete* RSS updates for a jurisdiction, we can rely on that. The API will tell us if that's the case via the `pacer_rss_entry_types` key here:

https://www.courtlistener.com/api/rest/v3/courts/?jurisdiction=FD&fields=id,pacer_has_rss_feed,pacer_rss_entry_types,full_name,jurisdiction

And finally, I have to mention that there is one more way of getting free updates from PACER that we're not yet supporting (but should): 

https://github.com/freelawproject/courtlistener/issues/1279

If we get that fixed, we won't have to poll dockets and can instead wait until they update, and gather data only after that point. This is on my list to get done (and I even did a bunch of work on it already), but it's not at the top yet.

**Comment by anseljh** [comment]
Right, it would use our fetch API.

BYOB (Bring Your Own Budget) could also be an option for some curators/journalists/newsrooms who are already trawling PACER themselves. Then they're the ones deciding how much to spend (and actually spending it through their own PACER account), but we're giving them a new tool and way to reach an audience. 🤔 For those up for it, it would resolve the allocation & accounting questions. But I think this would only be one of multiple funding options.

**Comment by mlissner** [comment]
I'm confused...how is this different than #16?

**Comment by mlissner** [comment]
I think I'm comfy closing this, but let's re-open if there's a nugget of a feature I missed.
