### ISSUE TITLE
Little Cases Bots

### ISSUE THREAD

**Issue by anseljh** [freelawproject/bigcases2#8]
Make additional accounts that post about a subset of followed cases, like "Patent Cases Bot" or "Insurrection Cases Bot," etc.

**Comment by mlissner** [comment]
I'm sort of hopeful this can work at a similar level of abstraction as slack and discord, but we'll see. In any case, when we do this, we'll want it to also work on the sponsorship page, so if you want to sponsor a particular bot, you can.

**Comment by mlissner** [comment]
We'll get to sponsorship eventually, and the rest of Little Cases bots is in other issues. Closing.
