### ISSUE TITLE
"none" in post title

### ISSUE THREAD

**Issue by anseljh** [freelawproject/bigcases2#92]
Mastodon post text is:

> New minute entry in FTX Trading Ltd.: none

https://law.builders/@bigcases/109910435103158273

Looks like it's maybe from this weird docket entry, between 753 and 754:

![image](https://user-images.githubusercontent.com/2075772/220998882-348448b6-3907-4276-afd7-06cd3af59690.png)

https://www.courtlistener.com/docket/65748821/ftx-trading-ltd/?filed_after=&filed_before=&entry_gte=&entry_lte=&order_by=desc#minute-entry-220141219

Might be a RECAP/crawling bug rather than a BCB bug, but we might want to at least catch it.

**Comment by mlissner** [comment]
Hm, my guess is that PACER had bad data temporarily and we caught that. Looking at the Docket History report, there's nothing like that:

![image](https://user-images.githubusercontent.com/236970/221012050-fd4e67ea-c6ca-4c41-801d-1ba69cc1fa81.png)

We could check the RSS feed data for this, but that's kind of a pain. I think the easier thing to do is add this to our regex that blocks bad tweets. 

What do you think, @ERosendo?

**Comment by ERosendo** [comment]
I agree! We can use the regex to avoid creating this kind of post.
